---
- src: znz.ufw
- src: https://github.com/znz/ansible-role-sshd
  version: master
  name: znz.sshd
- src: znz.unattended-upgrades
- src: https://github.com/znz/ansible-role-nadoka
  version: master
  name: znz.nadoka
- src: znz.timesyncd
- src: https://github.com/znz/ansible-role-openvpn-client
  version: master
  name: znz.openvpn-client
