---
- hosts: all
  become: no
  gather_facts: no
  vars_files:
  - vars/{{ stage }}.yml

  tasks:
  - name: 'Create host groups'
    zabbix_group:
      host_groups: '1 Bluetooth'
      login_user: "{{ zbx_login_user }}"
      login_password: "{{ zbx_login_password }}"
      server_url: "{{ zbx_server_url }}"
      state: present

  - name: '0 My Template Bluetooth'
    zabbix_template:
      login_user: "{{ zbx_login_user }}"
      login_password: "{{ zbx_login_password }}"
      server_url: "{{ zbx_server_url }}"
      timeout: 30
      state: present
      #link_templates:
      #macros:
      template_name: '0 My Template Bluetooth'
      template_groups:
      - '0 My Templates'
      template_json:
        zabbix_export:
          version: '4.0'
          groups:
          - name: '0 My Templates'
          templates:
          - applications:
            - name: 'Bluetooth'
            description: ''
            discovery_rules: []
            groups:
            - name: '0 My Templates'
            items:
            - allowed_hosts: ''
              applications:
              - name: 'Bluetooth'
              allow_traps: '0'
              authtype: '0'
              delay: '300s'
              description: ''
              follow_redirects: '1'
              headers: []
              history: '90d'
              http_proxy: ''
              inventory_link: '0'
              ipmi_sensor: ''
              jmx_endpoint: ''
              key: 'hcitool-name.sh["{$BT_MACADDR}"]'
              logtimefmt: ''
              master_item: ''
              name: 'Bluetooth name'
              output_format: '0'
              params: ''
              password: ''
              port: ''
              posts: ''
              post_type: '0'
              preprocessing: ''
              privatekey: ''
              publickey: ''
              query_fields: []
              request_method: '0'
              retrieve_mode: '0'
              snmp_community: ''
              snmp_oid: ''
              snmpv3_authpassphrase: ''
              snmpv3_authprotocol: '0'
              snmpv3_contextname: ''
              snmpv3_privpassphrase: ''
              snmpv3_privprotocol: '0'
              snmpv3_securitylevel: '0'
              snmpv3_securityname: ''
              ssl_cert_file: ''
              ssl_key_file: ''
              ssl_key_password: ''
              status: '0'
              status_codes: '200'
              timeout: '3s'
              trends: '0'
              type: '10'
              units: ''
              url: ''
              username: ''
              value_type: '1'
              valuemap: []
              verify_host: '0'
              verify_peer: '0'
            httptests: []
            macros: []
            name: '0 My Template Bluetooth'
            screens: []
            template: '0 My Template Bluetooth'
            templates: []
          triggers:
          - correlation_mode: '0'
            correlation_tag: ''
            dependencies: []
            description: ''
            expression: '{0 My Template Bluetooth:hcitool-name.sh["{$BT_MACADDR}"].diff()}=1'
            manual_close: '0'
            name: 'Bluetooth status changed'
            priority: '1'
            recovery_expression: ''
            recovery_mode: '0'
            status: '0'
            tags: []
            type: '0'
            url: ''

  - name: 'zabbix bluetooth hosts'
    with_items: '{{ zbx_bluetooth_hosts }}'
    zabbix_host:
      host_groups: '1 Bluetooth'
      host_name: '{{ item.host_name }}'
      interfaces:
      - dns: ''
        ip: '127.0.0.1'
        main: 1
        port: 10050
        type: agent
        useip: '1'
      link_templates: '0 My Template Bluetooth'
      login_user: "{{ zbx_login_user }}"
      login_password: "{{ zbx_login_password }}"
      # proxy:
      server_url: "{{ zbx_server_url }}"
      state: present
      status: "{{ item.status|default('enabled') }}"

  - name: 'zabbix bluetooth mac address'
    with_items: '{{ zbx_bluetooth_hosts }}'
    zabbix_hostmacro:
      host_name: '{{ item.host_name }}'
      macro_name: 'BT_MACADDR'
      macro_value: '{{ item.mac_address }}'
      login_user: "{{ zbx_login_user }}"
      login_password: "{{ zbx_login_password }}"
      # proxy:
      server_url: "{{ zbx_server_url }}"
      state: present
