---
- hosts: all
  become: no
  gather_facts: no
  vars_files:
  - vars/{{ stage }}.yml

  tasks:
  - name: '0 My Template OpenVPN'
    zabbix_template:
      login_user: "{{ zbx_login_user }}"
      login_password: "{{ zbx_login_password }}"
      server_url: "{{ zbx_server_url }}"
      timeout: 30
      state: present
      #link_templates:
      #macros:
      template_name: '0 My Template OpenVPN'
      template_groups:
      - '0 Certificate Templates'
      - '0 My Templates'
      template_json:
        zabbix_export:
          version: '4.0'
          groups:
          - name: '0 Certificate Templates'
          - name: '0 My Templates'
          templates:
          - applications:
            - name: 'Cert Remaining'
            description: ''
            discovery_rules: []
            groups:
            - name: '0 Certificate Templates'
            - name: '0 My Templates'
            items:
            - allowed_hosts: ''
              applications:
              - name: 'Cert Remaining'
              allow_traps: '0'
              authtype: '0'
              delay: '60m'
              description: ''
              follow_redirects: '1'
              headers: []
              history: '7d'
              http_proxy: ''
              inventory_link: '0'
              ipmi_sensor: ''
              jmx_endpoint: ''
              key: 'crl.next_update.openvpn-server'
              logtimefmt: ''
              master_item: ''
              name: 'OpenVPN CRL Remaining'
              output_format: '0'
              params: ''
              password: ''
              port: ''
              posts: ''
              post_type: '0'
              preprocessing: ''
              privatekey: ''
              publickey: ''
              query_fields: []
              request_method: '0'
              retrieve_mode: '0'
              snmp_community: ''
              snmp_oid: ''
              snmpv3_authpassphrase: ''
              snmpv3_authprotocol: '0'
              snmpv3_contextname: ''
              snmpv3_privpassphrase: ''
              snmpv3_privprotocol: '0'
              snmpv3_securitylevel: '0'
              snmpv3_securityname: ''
              ssl_cert_file: ''
              ssl_key_file: ''
              ssl_key_password: ''
              status: '0'
              status_codes: '200'
              timeout: '3s'
              trends: '3650d'
              type: '0'
              units: 'uptime'
              url: ''
              username: ''
              value_type: '0'
              valuemap: []
              verify_host: '0'
              verify_peer: '0'
            httptests: []
            macros: []
            name: '0 My Template OpenVPN'
            screens: []
            template: '0 My Template OpenVPN'
            templates: []
          triggers:
          - correlation_mode: '0'
            correlation_tag: ''
            dependencies: []
            description: ''
            expression: '{0 My Template OpenVPN:crl.next_update.openvpn-server.last(0)}<604800'
            manual_close: '0'
            name: 'CRL is about to expire on {HOST.NAME} (7 days)'
            priority: '4'
            recovery_expression: ''
            recovery_mode: '2'
            status: '0'
            tags: []
            type: '0'
            url: ''
          - correlation_mode: '0'
            correlation_tag: ''
            dependencies:
            - name: 'CRL is about to expire on {HOST.NAME} (7 days)'
              expression: '{0 My Template OpenVPN:crl.next_update.openvpn-server.last(0)}<604800'
              recovery_expression: ''
            description: ''
            expression: '{0 My Template OpenVPN:crl.next_update.openvpn-server.last(0)}<1209600'
            manual_close: '0'
            name: 'CRL is about to expire on {HOST.NAME} (14 days)'
            priority: '3'
            recovery_expression: ''
            recovery_mode: '2'
            status: '0'
            tags: []
            type: '0'
            url: ''
          - correlation_mode: '0'
            correlation_tag: ''
            dependencies:
            - name: 'CRL is about to expire on {HOST.NAME} (14 days)'
              expression: '{0 My Template OpenVPN:crl.next_update.openvpn-server.last(0)}<1209600'
              recovery_expression: ''
            description: ''
            expression: '{0 My Template OpenVPN:crl.next_update.openvpn-server.last(0)}<1814400'
            manual_close: '0'
            name: 'CRL is about to expire on {HOST.NAME} (21 days)'
            priority: '2'
            recovery_expression: ''
            recovery_mode: '2'
            status: '0'
            tags: []
            type: '0'
            url: ''
          - correlation_mode: '0'
            correlation_tag: ''
            dependencies:
            - name: 'CRL is about to expire on {HOST.NAME} (21 days)'
              expression: '{0 My Template OpenVPN:crl.next_update.openvpn-server.last(0)}<1814400'
              recovery_expression: ''
            description: ''
            expression: '{0 My Template OpenVPN:crl.next_update.openvpn-server.last(0)}<2678400'
            manual_close: '0'
            name: 'CRL is about to expire on {HOST.NAME} (31 days)'
            priority: '1'
            recovery_expression: ''
            recovery_mode: '2'
            status: '0'
            tags: []
            type: '0'
            url: ''
          - correlation_mode: '0'
            correlation_tag: ''
            dependencies:
            - name: 'CRL is about to expire on {HOST.NAME} (31 days)'
              expression: '{0 My Template OpenVPN:crl.next_update.openvpn-server.last(0)}<2678400'
              recovery_expression: ''
            description: ''
            expression: '{0 My Template OpenVPN:crl.next_update.openvpn-server.last(0)}<0'
            manual_close: '0'
            name: 'CRL is expired on {HOST.NAME}'
            priority: '5'
            recovery_expression: ''
            recovery_mode: '2'
            status: '0'
            tags: []
            type: '0'
            url: ''
          - correlation_mode: '0'
            correlation_tag: ''
            dependencies: []
            description: ''
            expression: '{0 My Template OpenVPN:crl.next_update.openvpn-server.change(0)}>0'
            manual_close: '0'
            name: 'CRL is renewal on {HOST.NAME}'
            priority: '1'
            recovery_expression: ''
            recovery_mode: '2'
            status: '0'
            tags: []
            type: '0'
            url: ''
