---
- hosts: all
  become: no
  gather_facts: no
  vars_files:
  - vars/{{ stage }}.yml

  tasks:
  - name: '0 Template nasne monitor'
    zabbix_template:
      login_user: "{{ zbx_login_user }}"
      login_password: "{{ zbx_login_password }}"
      server_url: "{{ zbx_server_url }}"
      state: present
      #link_templates:
      #macros:
      template_name: '0 Template nasne monitor'
      template_groups:
      - '0 My Templates'
      template_json:
        zabbix_export:
          version: '3.0'
          graphs:
          - graph_items:
            - calc_fnc: '2'
              color: '6666FF'
              drawtype: '0'
              item:
                host: '0 Template nasne monitor'
                key: 'nasne.hdd.used'
              sortorder: '0'
              type: '0'
              yaxisside: '0'
            - calc_fnc: '2'
              color: '66FF66'
              drawtype: '0'
              item:
                host: '0 Template nasne monitor'
                key: 'nasne.hdd.free'
              sortorder: '1'
              type: '0'
              yaxisside: '0'
            height: '200'
            name: 'nasne HDD usage'
            percent_left: '0.0000'
            percent_right: '0.0000'
            show_3d: '0'
            show_legend: '1'
            show_triggers: '1'
            show_work_period: '1'
            type: '1'
            width: '900'
            yaxismax: '100.0000'
            yaxismin: '0.0000'
            ymax_item_1: '0'
            ymax_type_1: '0'
            ymin_item_1: '0'
            ymin_type_1: '0'
          - graph_items:
            - calc_fnc: '2'
              color: '6666FF'
              drawtype: '0'
              item:
                host: '0 Template nasne monitor'
                key: 'nasne.hdd.used'
              sortorder: '0'
              type: '0'
              yaxisside: '0'
            - calc_fnc: '2'
              color: '66FF66'
              drawtype: '0'
              item:
                host: '0 Template nasne monitor'
                key: 'nasne.hdd.free'
              sortorder: '1'
              type: '0'
              yaxisside: '0'
            height: '300'
            name: 'nasne HDD Usage (%)'
            percent_left: '0.0000'
            percent_right: '0.0000'
            show_3d: '0'
            show_legend: '1'
            show_triggers: '0'
            show_work_period: '0'
            type: '2'
            width: '450'
            yaxismax: '0.0000'
            yaxismin: '0.0000'
            ymax_item_1: '0'
            ymax_type_1: '0'
            ymin_item_1: '0'
            ymin_type_1: '0'
          - graph_items:
            - calc_fnc: '2'
              color: '66FF66'
              drawtype: '5'
              item:
                host: '0 Template nasne monitor'
                key: 'nasne.status.play'
              sortorder: '0'
              type: '0'
              yaxisside: '0'
            - calc_fnc: '2'
              color: '9999FF'
              drawtype: '5'
              item:
                host: '0 Template nasne monitor'
                key: 'nasne.status.live'
              sortorder: '1'
              type: '0'
              yaxisside: '0'
            - calc_fnc: '2'
              color: 'FF6666'
              drawtype: '5'
              item:
                host: '0 Template nasne monitor'
                key: 'nasne.status.rec'
              sortorder: '2'
              type: '0'
              yaxisside: '0'
            height: '200'
            name: 'nasne status'
            percent_left: '0.0000'
            percent_right: '0.0000'
            show_3d: '0'
            show_legend: '1'
            show_triggers: '1'
            show_work_period: '1'
            type: '0'
            width: '900'
            yaxismax: '1.0000'
            yaxismin: '0.0000'
            ymax_item_1: '0'
            ymax_type_1: '1'
            ymin_item_1: '0'
            ymin_type_1: '1'
          groups:
          - name: '0 My Templates'
          templates:
          - applications:
            - name: 'nasne'
            description: ''
            discovery_rules: []
            groups:
            - name: '0 My Templates'
            items:
            - allowed_hosts: ''
              applications:
              - name: 'nasne'
              authtype: '0'
              data_type: '0'
              delay: '0'
              delay_flex: ''
              delta: '0'
              description: ''
              formula: '1'
              history: '90'
              inventory_link: '0'
              ipmi_sensor: ''
              key: 'nasne.hdd.free'
              logtimefmt: ''
              multiplier: '0'
              name: 'nasne HDD free'
              params: ''
              password: ''
              port: ''
              privatekey: ''
              publickey: ''
              snmp_community: ''
              snmp_oid: ''
              snmpv3_authpassphrase: ''
              snmpv3_authprotocol: '0'
              snmpv3_contextname: ''
              snmpv3_privpassphrase: ''
              snmpv3_privprotocol: '0'
              snmpv3_securitylevel: '0'
              snmpv3_securityname: ''
              status: '0'
              trends: '3650'
              type: '2'
              units: 'byte'
              username: ''
              value_type: '3'
              valuemap: []
            - allowed_hosts: ''
              applications:
              - name: 'nasne'
              authtype: '0'
              data_type: '0'
              delay: '60'
              delay_flex: ''
              delta: '0'
              description: ''
              formula: '1'
              history: '90'
              inventory_link: '0'
              ipmi_sensor: ''
              key: 'nasne.hdd.free.percent'
              logtimefmt: ''
              multiplier: '0'
              name: 'nasne HDD free (%)'
              params: '100*last("nasne.hdd.free")/(last("nasne.hdd.free")+last(nasne.hdd.used))'
              password: ''
              port: ''
              privatekey: ''
              publickey: ''
              snmp_community: ''
              snmp_oid: ''
              snmpv3_authpassphrase: ''
              snmpv3_authprotocol: '0'
              snmpv3_contextname: ''
              snmpv3_privpassphrase: ''
              snmpv3_privprotocol: '0'
              snmpv3_securitylevel: '0'
              snmpv3_securityname: ''
              status: '0'
              trends: '3650'
              type: '15'
              units: '%'
              username: ''
              value_type: '0'
              valuemap: []
            - allowed_hosts: ''
              applications:
              - name: 'nasne'
              authtype: '0'
              data_type: '0'
              delay: '0'
              delay_flex: ''
              delta: '0'
              description: ''
              formula: '1'
              history: '90'
              inventory_link: '0'
              ipmi_sensor: ''
              key: 'nasne.hdd.used'
              logtimefmt: ''
              multiplier: '0'
              name: 'nasne HDD used'
              params: ''
              password: ''
              port: ''
              privatekey: ''
              publickey: ''
              snmp_community: ''
              snmp_oid: ''
              snmpv3_authpassphrase: ''
              snmpv3_authprotocol: '0'
              snmpv3_contextname: ''
              snmpv3_privpassphrase: ''
              snmpv3_privprotocol: '0'
              snmpv3_securitylevel: '0'
              snmpv3_securityname: ''
              status: '0'
              trends: '3650'
              type: '2'
              units: 'byte'
              username: ''
              value_type: '3'
              valuemap: []
            - allowed_hosts: ''
              applications:
              - name: 'nasne'
              authtype: '0'
              data_type: '0'
              delay: '60'
              delay_flex: ''
              delta: '0'
              description: ''
              formula: '1'
              history: '90'
              inventory_link: '0'
              ipmi_sensor: ''
              key: 'nasne.hdd.used.percent'
              logtimefmt: ''
              multiplier: '0'
              name: 'nasne HDD used (%)'
              params: '100*last("nasne.hdd.used")/(last("nasne.hdd.free")+last(nasne.hdd.used))'
              password: ''
              port: ''
              privatekey: ''
              publickey: ''
              snmp_community: ''
              snmp_oid: ''
              snmpv3_authpassphrase: ''
              snmpv3_authprotocol: '0'
              snmpv3_contextname: ''
              snmpv3_privpassphrase: ''
              snmpv3_privprotocol: '0'
              snmpv3_securitylevel: '0'
              snmpv3_securityname: ''
              status: '0'
              trends: '3650'
              type: '15'
              units: '%'
              username: ''
              value_type: '0'
              valuemap: []
            - allowed_hosts: ''
              applications:
              - name: 'nasne'
              authtype: '0'
              data_type: '0'
              delay: '0'
              delay_flex: ''
              delta: '0'
              description: ''
              formula: '1'
              history: '365'
              inventory_link: '0'
              ipmi_sensor: ''
              key: 'nasne.log.rec'
              logtimefmt: 'yyyy-MM-ddThh:mm:ss+09:00'
              multiplier: '0'
              name: 'nasne recording log'
              params: ''
              password: ''
              port: ''
              privatekey: ''
              publickey: ''
              snmp_community: ''
              snmp_oid: ''
              snmpv3_authpassphrase: ''
              snmpv3_authprotocol: '0'
              snmpv3_contextname: ''
              snmpv3_privpassphrase: ''
              snmpv3_privprotocol: '0'
              snmpv3_securitylevel: '0'
              snmpv3_securityname: ''
              status: '0'
              trends: '0'
              type: '2'
              units: ''
              username: ''
              value_type: '2'
              valuemap: []
            - allowed_hosts: ''
              applications:
              - name: 'nasne'
              authtype: '0'
              data_type: '0'
              delay: '0'
              delay_flex: ''
              delta: '0'
              description: ''
              formula: '1'
              history: '90'
              inventory_link: '0'
              ipmi_sensor: ''
              key: 'nasne.status.live'
              logtimefmt: ''
              multiplier: '0'
              name: 'nasne LIVE'
              params: ''
              password: ''
              port: ''
              privatekey: ''
              publickey: ''
              snmp_community: ''
              snmp_oid: ''
              snmpv3_authpassphrase: ''
              snmpv3_authprotocol: '0'
              snmpv3_contextname: ''
              snmpv3_privpassphrase: ''
              snmpv3_privprotocol: '0'
              snmpv3_securitylevel: '0'
              snmpv3_securityname: ''
              status: '0'
              trends: '3650'
              type: '2'
              units: ''
              username: ''
              value_type: '3'
              valuemap: []
            - allowed_hosts: ''
              applications:
              - name: 'nasne'
              authtype: '0'
              data_type: '0'
              delay: '0'
              delay_flex: ''
              delta: '0'
              description: ''
              formula: '1'
              history: '90'
              inventory_link: '0'
              ipmi_sensor: ''
              key: 'nasne.status.play'
              logtimefmt: ''
              multiplier: '0'
              name: 'nasne PLAY'
              params: ''
              password: ''
              port: ''
              privatekey: ''
              publickey: ''
              snmp_community: ''
              snmp_oid: ''
              snmpv3_authpassphrase: ''
              snmpv3_authprotocol: '0'
              snmpv3_contextname: ''
              snmpv3_privpassphrase: ''
              snmpv3_privprotocol: '0'
              snmpv3_securitylevel: '0'
              snmpv3_securityname: ''
              status: '0'
              trends: '3650'
              type: '2'
              units: ''
              username: ''
              value_type: '3'
              valuemap: []
            - allowed_hosts: ''
              applications:
              - name: 'nasne'
              authtype: '0'
              data_type: '0'
              delay: '0'
              delay_flex: ''
              delta: '0'
              description: ''
              formula: '1'
              history: '90'
              inventory_link: '0'
              ipmi_sensor: ''
              key: 'nasne.status.rec'
              logtimefmt: ''
              multiplier: '0'
              name: 'nasne REC'
              params: ''
              password: ''
              port: ''
              privatekey: ''
              publickey: ''
              snmp_community: ''
              snmp_oid: ''
              snmpv3_authpassphrase: ''
              snmpv3_authprotocol: '0'
              snmpv3_contextname: ''
              snmpv3_privpassphrase: ''
              snmpv3_privprotocol: '0'
              snmpv3_securitylevel: '0'
              snmpv3_securityname: ''
              status: '0'
              trends: '3650'
              type: '2'
              units: ''
              username: ''
              value_type: '3'
              valuemap: []
            macros: []
            name: '0 Template nasne monitor'
            screens:
            - hsize: '1'
              name: 'nasne disk usage and status'
              screen_items:
              - application: ''
                colspan: '1'
                dynamic: '0'
                elements: '0'
                halign: '0'
                height: '80'
                max_columns: '3'
                resource:
                  host: '0 Template nasne monitor'
                  name: 'nasne HDD usage'
                resourcetype: '0'
                rowspan: '1'
                sort_triggers: '0'
                style: '0'
                url: ''
                valign: '0'
                width: '800'
                x: '0'
                y: '0'
              - application: ''
                colspan: '1'
                dynamic: '0'
                elements: '0'
                halign: '0'
                height: '130'
                max_columns: '3'
                resource:
                  host: '0 Template nasne monitor'
                  name: 'nasne status'
                resourcetype: '0'
                rowspan: '1'
                sort_triggers: '0'
                style: '0'
                url: ''
                valign: '0'
                width: '800'
                x: '0'
                y: '1'
              vsize: '2'
            template: '0 Template nasne monitor'
            templates: []
          triggers:
          - dependencies: []
            description: ''
            expression: '{0 Template nasne monitor:nasne.hdd.free.percent.last()}<1'
            name: 'disk free < 1%'
            priority: '4'
            status: '0'
            type: '0'
            url: ''
          - dependencies:
            - name: 'disk free < 1%'
              expression: '{0 Template nasne monitor:nasne.hdd.free.percent.last()}<1'
            description: ''
            expression: '{0 Template nasne monitor:nasne.hdd.free.percent.last()}<3'
            name: 'disk free < 3%'
            priority: '3'
            status: '0'
            type: '0'
            url: ''
          - dependencies:
            - name: 'disk free < 3%'
              expression: '{0 Template nasne monitor:nasne.hdd.free.percent.last()}<3'
            description: ''
            expression: '{0 Template nasne monitor:nasne.hdd.free.percent.last()}<5'
            name: 'disk free < 5%'
            priority: '2'
            status: '0'
            type: '0'
            url: ''
#          - dependencies:
#            - name: 'disk free < 5%'
#              expression: '{0 Template nasne monitor:nasne.hdd.free.percent.last()}<5'
#            description: ''
#            expression: '{0 Template nasne monitor:nasne.hdd.free.percent.last()}<10'
#            name: 'disk free < 10%'
#            priority: '1'
#            status: '0'
#            type: '0'
#            url: ''
#          - dependencies: []
#            description: ''
#            expression: '{0 Template nasne monitor:nasne.log.rec.diff(0)}=1'
#            name: 'Recording start'
#            priority: '1'
#            status: '0'
#            type: '0'
#            url: ''
